version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: pokemon_pg
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokemon_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pokemon_net

  backend:
    build: .
    container_name: pokemon_backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/pokemon_db?schema=public
      JWT_SECRET: ${JWT_SECRET:-dev_secret_key}
    depends_on:
      - postgres
    networks:
      - pokemon_net

volumes:
  postgres_data:


networks:
  pokemon_net:
